In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Cargar el dataset
df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car.csv')

# Dividir en conjunto de entrenamiento (70%), validación (15%) y prueba (15%)
train_df, temp_df = train_test_split(df, test_size=0.3, stratify=df['acceptability'], random_state=42)
valid_df, test_df = train_test_split(temp_df, test_size=0.5, stratify=temp_df['acceptability'], random_state=42)

# Guardar los conjuntos en archivos CSV
train_df.to_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_train.csv', index=False)
valid_df.to_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_valid.csv', index=False)
test_df.to_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_test.csv', index=False)

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder

# Cargar los datasets
train_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_train.csv')
valid_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_valid.csv')
test_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_test.csv')

# Obtener características y etiquetas
X_train = train_df.drop('acceptability', axis=1)
y_train = train_df['acceptability']
X_valid = valid_df.drop('acceptability', axis=1)
y_valid = valid_df['acceptability']

# Preprocesamiento de las etiquetas utilizando LabelEncoder
lab_enc = LabelEncoder()
lab_enc.fit(y_train)
y_train_encoded = lab_enc.transform(y_train)
y_valid_encoded = lab_enc.transform(y_valid)

# Preprocesamiento de características utilizando pd.get_dummies()
X_train_encoded = pd.get_dummies(X_train, drop_first=True)
X_valid_encoded = pd.get_dummies(X_valid, drop_first=True)

# Definir los valores de lambda a probar
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}
lambda_values = [1 / C for C in param_grid['C']]

# Inicializar el modelo de regresión logística
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)

# Realizar búsqueda en la cuadrícula para encontrar el mejor valor de C
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='f1_macro')
grid_search.fit(X_train_encoded, y_train_encoded)

# Obtener el mejor valor de C
best_C = grid_search.best_params_['C']

# Entrenar el modelo de regresión logística con el mejor valor de C
best_model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000, C=best_C)
best_model.fit(X_train_encoded, y_train_encoded)

# Predecir las etiquetas en el conjunto de validación
y_pred = best_model.predict(X_valid_encoded)

# Calcular el f1-score en el conjunto de validación
f1_macro = f1_score(y_valid_encoded, y_pred, average='macro')

print("El mejor valor de C encontrado:", best_C)
print("F1-score macro en el conjunto de validación:", f1_macro)


El mejor valor de C encontrado: 100
F1-score macro en el conjunto de validación: 0.8961993922468231


In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder

# Cargar los datasets
train_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_train.csv')
valid_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_valid.csv')
test_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_test.csv')

# Obtener características y etiquetas
X_train = train_df.drop('acceptability', axis=1)
y_train = train_df['acceptability']
X_valid = valid_df.drop('acceptability', axis=1)
y_valid = valid_df['acceptability']

# Preprocesamiento de las etiquetas utilizando LabelEncoder
lab_enc = LabelEncoder()
lab_enc.fit(y_train)
y_train_encoded = lab_enc.transform(y_train)
y_valid_encoded = lab_enc.transform(y_valid)

# Preprocesamiento de características utilizando pd.get_dummies()
X_train_encoded = pd.get_dummies(X_train, drop_first=True)
X_valid_encoded = pd.get_dummies(X_valid, drop_first=True)

# Definir los valores de lambda a probar
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}
lambda_values = [1 / C for C in param_grid['C']]

# Inicializar el modelo de regresión logística
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)

# Realizar búsqueda en la cuadrícula para encontrar el mejor valor de C
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='f1_macro')
grid_search.fit(X_train_encoded, y_train_encoded)

# Obtener el mejor valor de C
best_C = grid_search.best_params_['C']

# Entrenar el modelo de regresión logística con el mejor valor de C
best_model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000, C=best_C)
best_model.fit(X_train_encoded, y_train_encoded)

# Predecir las etiquetas en el conjunto de validación
y_pred = best_model.predict(X_valid_encoded)

# Calcular las métricas de evaluación
conf_matrix = confusion_matrix(y_valid_encoded, y_pred)
accuracy = accuracy_score(y_valid_encoded, y_pred)
precision = precision_score(y_valid_encoded, y_pred, average=None)
recall = recall_score(y_valid_encoded, y_pred, average=None)
f1 = f1_score(y_valid_encoded, y_pred, average=None)

# Imprimir la matriz de confusión y las métricas de evaluación por clase
print("Matriz de Confusión:")
print(conf_matrix)
print("\nAccuracy:", accuracy)
print("\nPrecision por clase:", precision)
print("\nRecall por clase:", recall)
print("\nF1-score por clase:", f1)


Matriz de Confusión:
[[ 49   1   5   2]
 [  1  10   0   0]
 [  4   0 177   0]
 [  0   1   0   9]]

Accuracy: 0.9459459459459459

Precision por clase: [0.90740741 0.83333333 0.97252747 0.81818182]

Recall por clase: [0.85964912 0.90909091 0.97790055 0.9       ]

F1-score por clase: [0.88288288 0.86956522 0.97520661 0.85714286]


In [5]:
# Calculate True Positive Rate (TPR) per class
def true_positive_rate_per_class(conf_matrix):
    tpr_per_class = []
    for i in range(conf_matrix.shape[0]):
        true_positive = conf_matrix[i, i]
        false_negative = np.sum(conf_matrix[i, :]) - true_positive
        tpr = true_positive / (true_positive + false_negative)
        tpr_per_class.append(tpr)
    return tpr_per_class

# Calculate True Positive Rate (TPR) per class on the validation set
tpr_valid = true_positive_rate_per_class(conf_matrix)
print("True Positive Rate (TPR) per class on the validation set:")
for i, tpr in enumerate(tpr_valid):
    print(f"Class {i}: {tpr * 100:.2f}%")


True Positive Rate (TPR) per class on the validation set:
Class 0: 85.96%
Class 1: 90.91%
Class 2: 97.79%
Class 3: 90.00%


In [6]:
# Obtener características y etiquetas del conjunto de prueba
X_test = test_df.drop('acceptability', axis=1)
y_test = test_df['acceptability']

# Preprocesamiento de las etiquetas utilizando LabelEncoder
y_test_encoded = lab_enc.transform(y_test)

# Preprocesamiento de características utilizando pd.get_dummies()
X_test_encoded = pd.get_dummies(X_test, drop_first=True)

# Predecir las etiquetas en el conjunto de prueba
y_pred_test = best_model.predict(X_test_encoded)

# Calcular las métricas de evaluación en el conjunto de prueba
conf_matrix_test = confusion_matrix(y_test_encoded, y_pred_test)
accuracy_test = accuracy_score(y_test_encoded, y_pred_test)
precision_test = precision_score(y_test_encoded, y_pred_test, average=None)
recall_test = recall_score(y_test_encoded, y_pred_test, average=None)
f1_test = f1_score(y_test_encoded, y_pred_test, average=None)

# Imprimir la matriz de confusión y las métricas de evaluación por clase en el conjunto de prueba
print("Matriz de Confusión en el conjunto de prueba:")
print(conf_matrix_test)
print("\nAccuracy en el conjunto de prueba:", accuracy_test)
print("\nPrecision por clase en el conjunto de prueba:", precision_test)
print("\nRecall por clase en el conjunto de prueba:", recall_test)
print("\nF1-score por clase en el conjunto de prueba:", f1_test)

# Comparación con las métricas reportadas en el conjunto de validación
print("\nComparación con las métricas reportadas en el conjunto de validación:")
print("Diferencia en Accuracy:", accuracy_test - accuracy)
print("Diferencia en Precision por clase:", precision_test - precision)
print("Diferencia en Recall por clase:", recall_test - recall)
print("Diferencia en F1-score por clase:", f1_test - f1)

Matriz de Confusión en el conjunto de prueba:
[[ 53   0   4   1]
 [  2   8   0   0]
 [  7   0 175   0]
 [  0   0   0  10]]

Accuracy en el conjunto de prueba: 0.9461538461538461

Precision por clase en el conjunto de prueba: [0.85483871 1.         0.97765363 0.90909091]

Recall por clase en el conjunto de prueba: [0.9137931  0.8        0.96153846 1.        ]

F1-score por clase en el conjunto de prueba: [0.88333333 0.88888889 0.96952909 0.95238095]

Comparación con las métricas reportadas en el conjunto de validación:
Diferencia en Accuracy: 0.00020790020790018016
Diferencia en Precision por clase: [-0.0525687   0.16666667  0.00512616  0.09090909]
Diferencia en Recall por clase: [ 0.05414398 -0.10909091 -0.01636209  0.1       ]
Diferencia en F1-score por clase: [ 0.00045045  0.01932367 -0.00567753  0.0952381 ]


In [7]:
# Calculate True Positive Rate (TPR) per class on the test set
tpr_test = true_positive_rate_per_class(conf_matrix_test)
print("\nTrue Positive Rate (TPR) per class on the test set:")
for i, tpr in enumerate(tpr_test):
    print(f"Class {i}: {tpr * 100:.2f}%")


True Positive Rate (TPR) per class on the test set:
Class 0: 91.38%
Class 1: 80.00%
Class 2: 96.15%
Class 3: 100.00%


## Decision tree

In [8]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder

# Cargar los datasets
train_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_train.csv')
valid_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_valid.csv')
test_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_test.csv')

# Obtener características y etiquetas
X_train = train_df.drop('acceptability', axis=1)
y_train = train_df['acceptability']
X_valid = valid_df.drop('acceptability', axis=1)
y_valid = valid_df['acceptability']

# Preprocesamiento de las etiquetas utilizando LabelEncoder
lab_enc = LabelEncoder()
lab_enc.fit(y_train)
y_train_encoded = lab_enc.transform(y_train)
y_valid_encoded = lab_enc.transform(y_valid)

# Preprocesamiento de características utilizando pd.get_dummies()
X_train_encoded = pd.get_dummies(X_train, drop_first=True)
X_valid_encoded = pd.get_dummies(X_valid, drop_first=True)

# Definir los hiperparámetros a probar
param_grid = {'max_depth': [None, 5, 10, 15, 20], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4]}

# Inicializar el modelo de árbol de decisión
model = DecisionTreeClassifier()

# Realizar búsqueda en la cuadrícula para encontrar los mejores hiperparámetros
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='f1_macro')
grid_search.fit(X_train_encoded, y_train_encoded)

# Obtener los mejores hiperparámetros
best_params = grid_search.best_params_

# Entrenar el modelo de árbol de decisión con los mejores hiperparámetros
best_model = DecisionTreeClassifier(**best_params)
best_model.fit(X_train_encoded, y_train_encoded)

# Predecir las etiquetas en el conjunto de validación
y_pred = best_model.predict(X_valid_encoded)

# Calcular las métricas de evaluación
conf_matrix = confusion_matrix(y_valid_encoded, y_pred)
accuracy = accuracy_score(y_valid_encoded, y_pred)
precision = precision_score(y_valid_encoded, y_pred, average=None)
recall = recall_score(y_valid_encoded, y_pred, average=None)
f1 = f1_score(y_valid_encoded, y_pred, average=None)

# Imprimir la matriz de confusión y las métricas de evaluación por clase
print("Matriz de Confusión:")
print(conf_matrix)
print("\nAccuracy:", accuracy)
print("\nPrecision por clase:", precision)
print("\nRecall por clase:", recall)
print("\nF1-score por clase:", f1)

# Obtener características y etiquetas del conjunto de prueba
X_test = test_df.drop('acceptability', axis=1)
y_test = test_df['acceptability']

# Preprocesamiento de características utilizando pd.get_dummies()
X_test_encoded = pd.get_dummies(X_test, drop_first=True)

# Predecir las etiquetas en el conjunto de prueba
y_pred_test = best_model.predict(X_test_encoded)

# Preprocesamiento de las etiquetas utilizando LabelEncoder
y_test_encoded = lab_enc.transform(y_test)

# Calcular las métricas de evaluación en el conjunto de prueba
conf_matrix_test = confusion_matrix(y_test_encoded, y_pred_test)
accuracy_test = accuracy_score(y_test_encoded, y_pred_test)
precision_test = precision_score(y_test_encoded, y_pred_test, average=None)
recall_test = recall_score(y_test_encoded, y_pred_test, average=None)
f1_test = f1_score(y_test_encoded, y_pred_test, average=None)

# Imprimir la matriz de confusión y las métricas de evaluación por clase en el conjunto de prueba
print("\nMatriz de Confusión en el conjunto de prueba:")
print(conf_matrix_test)
print("\nAccuracy en el conjunto de prueba:", accuracy_test)
print("\nPrecision por clase en el conjunto de prueba:", precision_test)
print("\nRecall por clase en el conjunto de prueba:", recall_test)
print("\nF1-score por clase en el conjunto de prueba:", f1_test)

# Comparación con las métricas reportadas en el conjunto de validación
print("\nComparación con las métricas reportadas en el conjunto de validación:")
print("Diferencia en Accuracy:", accuracy_test - accuracy)
print("Diferencia en Precision por clase:", precision_test - precision)
print("Diferencia en Recall por clase:", recall_test - recall)
print("Diferencia en F1-score por clase:", f1_test - f1)

# Calculate True Positive Rate (TPR) per class on the validation set
tpr_valid = true_positive_rate_per_class(conf_matrix)
print("True Positive Rate (TPR) per class on the validation set:")
for i, tpr in enumerate(tpr_valid):
    print(f"Class {i}: {tpr * 100:.2f}%")

# Calculate True Positive Rate (TPR) per class on the test set
tpr_test = true_positive_rate_per_class(conf_matrix_test)
print("\nTrue Positive Rate (TPR) per class on the test set:")
for i, tpr in enumerate(tpr_test):
    print(f"Class {i}: {tpr * 100:.2f}%")

Matriz de Confusión:
[[ 48   2   7   0]
 [  5   5   0   1]
 [  9   0 172   0]
 [  1   1   0   8]]

Accuracy: 0.8996138996138996

Precision por clase: [0.76190476 0.625      0.96089385 0.88888889]

Recall por clase: [0.84210526 0.45454545 0.95027624 0.8       ]

F1-score por clase: [0.8        0.52631579 0.95555556 0.84210526]

Matriz de Confusión en el conjunto de prueba:
[[ 51   1   6   0]
 [  6   4   0   0]
 [  2   0 180   0]
 [  0   0   0  10]]

Accuracy en el conjunto de prueba: 0.9423076923076923

Precision por clase en el conjunto de prueba: [0.86440678 0.8        0.96774194 1.        ]

Recall por clase en el conjunto de prueba: [0.87931034 0.4        0.98901099 1.        ]

F1-score por clase en el conjunto de prueba: [0.87179487 0.53333333 0.97826087 1.        ]

Comparación con las métricas reportadas en el conjunto de validación:
Diferencia en Accuracy: 0.0426937926937927
Diferencia en Precision por clase: [0.10250202 0.175      0.00684808 0.11111111]
Diferencia en Recall po

## MLP

In [10]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder

# Function to calculate True Positive Rate (TPR) per class
def true_positive_rate_per_class(conf_matrix):
    tpr_per_class = []
    for i in range(conf_matrix.shape[0]):
        true_positive = conf_matrix[i, i]
        false_negative = np.sum(conf_matrix[i, :]) - true_positive
        tpr = true_positive / (true_positive + false_negative)
        tpr_per_class.append(tpr)
    return tpr_per_class

# Load datasets
train_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_train.csv')
valid_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_valid.csv')
test_df = pd.read_csv('/home/linar/Desktop/ML/Clases/Clase 3/i302/TP3/Data/3 - Vehicle Acceptability Evaluation/car_test.csv')

# Extract features and labels
X_train = train_df.drop('acceptability', axis=1)
y_train = train_df['acceptability']
X_valid = valid_df.drop('acceptability', axis=1)
y_valid = valid_df['acceptability']

# Preprocess labels using LabelEncoder
lab_enc = LabelEncoder()
lab_enc.fit(y_train)
y_train_encoded = lab_enc.transform(y_train)
y_valid_encoded = lab_enc.transform(y_valid)

# Preprocess features using pd.get_dummies()
X_train_encoded = pd.get_dummies(X_train, drop_first=True)
X_valid_encoded = pd.get_dummies(X_valid, drop_first=True)

# Define MLPClassifier parameters
mlp_params = {'hidden_layer_sizes': (100, 50), 'max_iter': 1000, 'random_state': 1}

# Initialize MLPClassifier
model = MLPClassifier(**mlp_params)

# Train MLPClassifier
model.fit(X_train_encoded, y_train_encoded)

# Predict labels on the validation set
y_pred_valid = model.predict(X_valid_encoded)

# Calculate evaluation metrics on the validation set
conf_matrix_valid = confusion_matrix(y_valid_encoded, y_pred_valid)
accuracy_valid = accuracy_score(y_valid_encoded, y_pred_valid)
precision_valid = precision_score(y_valid_encoded, y_pred_valid, average=None)
recall_valid = recall_score(y_valid_encoded, y_pred_valid, average=None)
f1_valid = f1_score(y_valid_encoded, y_pred_valid, average=None)

# Print evaluation metrics on the validation set
print("Evaluation metrics on the validation set:")
print("Confusion Matrix:")
print(conf_matrix_valid)
print("Accuracy:", accuracy_valid)
print("Precision per class:", precision_valid)
print("Recall per class:", recall_valid)
print("F1-score per class:", f1_valid)

# Extract features and labels from the test set
X_test = test_df.drop('acceptability', axis=1)
y_test = test_df['acceptability']

# Preprocess features using pd.get_dummies()
X_test_encoded = pd.get_dummies(X_test, drop_first=True)

# Predict labels on the test set
y_pred_test = model.predict(X_test_encoded)

# Preprocess labels using LabelEncoder
y_test_encoded = lab_enc.transform(y_test)

# Calculate evaluation metrics on the test set
conf_matrix_test = confusion_matrix(y_test_encoded, y_pred_test)
accuracy_test = accuracy_score(y_test_encoded, y_pred_test)
precision_test = precision_score(y_test_encoded, y_pred_test, average=None)
recall_test = recall_score(y_test_encoded, y_pred_test, average=None)
f1_test = f1_score(y_test_encoded, y_pred_test, average=None)

# Print evaluation metrics on the test set
print("\nEvaluation metrics on the test set:")
print("Confusion Matrix:")
print(conf_matrix_test)
print("Accuracy:", accuracy_test)
print("Precision per class:", precision_test)
print("Recall per class:", recall_test)
print("F1-score per class:", f1_test)

# Calculate True Positive Rate (TPR) per class on the validation set
tpr_valid = true_positive_rate_per_class(conf_matrix_valid)
print("\nTrue Positive Rate (TPR) per class on the validation set:")
for i, tpr in enumerate(tpr_valid):
    print(f"Class {i}: {tpr * 100:.2f}%")

# Calculate True Positive Rate (TPR) per class on the test set
tpr_test = true_positive_rate_per_class(conf_matrix_test)
print("\nTrue Positive Rate (TPR) per class on the test set:")
for i, tpr in enumerate(tpr_test):
    print(f"Class {i}: {tpr * 100:.2f}%")


Evaluation metrics on the validation set:
Confusion Matrix:
[[ 56   0   1   0]
 [  0  11   0   0]
 [  0   0 181   0]
 [  0   0   0  10]]
Accuracy: 0.9961389961389961
Precision per class: [1.         1.         0.99450549 1.        ]
Recall per class: [0.98245614 1.         1.         1.        ]
F1-score per class: [0.99115044 1.         0.99724518 1.        ]

Evaluation metrics on the test set:
Confusion Matrix:
[[ 56   0   2   0]
 [  0  10   0   0]
 [  1   0 181   0]
 [  0   0   0  10]]
Accuracy: 0.9884615384615385
Precision per class: [0.98245614 1.         0.98907104 1.        ]
Recall per class: [0.96551724 1.         0.99450549 1.        ]
F1-score per class: [0.97391304 1.         0.99178082 1.        ]

True Positive Rate (TPR) per class on the validation set:
Class 0: 98.25%
Class 1: 100.00%
Class 2: 100.00%
Class 3: 100.00%

True Positive Rate (TPR) per class on the test set:
Class 0: 96.55%
Class 1: 100.00%
Class 2: 99.45%
Class 3: 100.00%
