<center>
  <h1>Introducción a NumPy</h1>
  <h2>I302 - Aprendizaje Automático y Aprendizaje Profundo</h2>
  <h4>Universidad de San Andrés </h4>
</center>



Para usar NumPy, debemos importarla con:

In [1]:
import numpy as np

## Arrays

Los arreglos de NumPy son creados llamando al método array() de la biblioteca de NumPy. Cómo argumento del método, se debe pasar una lista.

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Hay diferentes tipos de arreglos en diferentes dimensiones. Pueden ser de una dimension (vectores), dos dimensiones (matrices), o n-dimensionales

In [3]:
# Uni-dimensional (vectores)
uni_dimensional = np.array([1,2,3])
print(uni_dimensional.shape)

# dos-dimensional (matrices)
dos_dimensional = np.array([[1,2,3], [1,2,3], [1,2,3]])
print(dos_dimensional.shape)

# tri-dimensional (tensores de orden 3)
tres_dimensional = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])
print(tres_dimensional.shape)

(3,)
(3, 3)
(3, 2, 3)


In [4]:
# Ojo, no es lo mismo un vector unidimensional, que una matriz columna o matriz fila
uni_dimensional = np.array([1,2,3])
print(uni_dimensional.shape)

matriz_fila = uni_dimensional.reshape(-1, 1) # -1 : no especificado, se infiere que debe ser 3
print(matriz_fila.shape)

matriz_columna = uni_dimensional.reshape(1, -1)
print(matriz_columna.shape)

(3,)
(3, 1)
(1, 3)


## Slicing

Los array se pueden hacer cortes para obtener sub arrays

In [5]:
vector = np.array([1,2,3,4,5,6])
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(f"El primer elemento de vector es {vector[0]} y el anteultimo es {vector[-2]}")
print(f"La segunda fila de matriz es {matriz[1,:]}, la primer columna es {matriz[:,0]}")
print(f"y podemos sacar submatrices tal como:")
print(matriz[:2, :2]) # Todas las filas hasta la 3 no inclusive, todas las columnas hasta la 3 no inclusive

El primer elemento de vector es 1 y el anteultimo es 5
La segunda fila de matriz es [4 5 6], la primer columna es [1 4 7]
y podemos sacar submatrices tal como:
[[1 2]
 [4 5]]


In [6]:
# Puedo cambiar elementos
vector = np.array([1,2,3,4,5,6])
print(vector)

[1 2 3 4 5 6]


In [7]:
vector[2] = 200
print(vector)

[  1   2 200   4   5   6]


In [8]:
vector[2:4] = [0, 0]
print(vector)

[1 2 0 0 5 6]


In [9]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
matriz[2, 1] = 900 # Cambio el elemento de la fila 3, columna 1 (elemento 8 antes)
print(matriz)

[[  1   2   3]
 [  4   5   6]
 [  7 900   9]]


In [11]:
matriz[: , -1] = [0, 0, 0] # Redefino todos los elementos de la última columna
print(matriz)

[[  1   2   0]
 [  4   5   0]
 [  7 900   0]]


In [12]:
matriz[1:3 , -3:-1] = [[7, 8], [8, 7]]
print(matriz)

[[1 2 0]
 [7 8 0]
 [8 7 0]]


Con NumPy contamos de formas de agregar o quitar elementos. Pero como es un array, en realidad crea una nueva copia

In [13]:
vector = np.array([1, 2, 3, 4])
print(vector)

[1 2 3 4]


Append

In [14]:
vector2 = np.append(vector, 5) # a "vector" le agrego el elemento 5, y lo guardo en "vector2"
print(vector)
print(vector2)

[1 2 3 4]
[1 2 3 4 5]


In [15]:
vector2 = np.append(vector, [10, 11, 12])
print(vector2)

[ 1  2  3  4 10 11 12]


In [16]:
matriz = np.array([[1,2,3], [4,5,6]])
print(matriz)

[[1 2 3]
 [4 5 6]]


In [17]:
matriz2 = np.append(matriz, 5)
print(matriz2)

[1 2 3 4 5 6 5]


In [18]:
matriz2 = np.append(matriz, [[6, 7, 8]], axis=0) # axis=0 lo agrega como nueva fila
print(matriz2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [19]:
matriz2 = np.append(matriz, [[6], [7]], axis=1) # axis=1 lo agrega como nueva columna
print(matriz2)

[[1 2 3 6]
 [4 5 6 7]]


Insert

In [20]:
matriz = np.array([[1, 1], [2, 2], [3, 3]])
print(matriz)

[[1 1]
 [2 2]
 [3 3]]


In [21]:
matriz2 = np.insert(matriz, 1, 5)
print(matriz2)

[1 5 1 2 2 3 3]


In [22]:
matriz2 = np.insert(matriz, 2, [[5,6]], axis=0) # Le digo en donde quiero agregarlo
print(matriz2)

[[1 1]
 [2 2]
 [5 6]
 [3 3]]


In [23]:
matriz2 = np.insert(matriz, [1], [[5],[6],[7]], axis=1)
print(matriz2)

[[1 5 1]
 [2 6 2]
 [3 7 3]]


Delete

In [24]:
matriz = np.array([[1, 1], [2, 2], [3, 3]])
print(matriz)

[[1 1]
 [2 2]
 [3 3]]


In [25]:
matriz2 = np.delete(matriz, 1, 0) # Elimino fila 1
print(matriz2)

[[1 1]
 [3 3]]


In [26]:
matriz2 = np.delete(matriz, 2, 0) # Elimino fila 2
print(matriz2)

[[1 1]
 [2 2]]


In [27]:
matriz2 = np.delete(matriz, 1, 1) # Elimino columna 2
print(matriz2)

[[1]
 [2]
 [3]]


In [28]:
matriz2 = np.delete(matriz, 0, None) #If axis is None, obj is applied to the flattened array.
print(matriz2)

[1 2 2 3 3]


In [29]:
matriz2 = np.delete(matriz, [0, 2], None)
print(matriz2)

[1 2 3 3]


# Tipos

La forma de que NumPy es muy eficiente en sus cálculos es que obliga a que los datos de los array sean del mismo tipo, es decir que implementa un array tradicional.

El atributo `dtype` nos permite ver que tipo de variable esta conformado el array.

In [30]:
ejemplo1 = np.array([1, 2, 3])
print(f"El ejemplo 1 es del tipo {ejemplo1.dtype}")

ejemplo2 = np.array([1, 2., 3])
print(f"El ejemplo 2 es del tipo {ejemplo2.dtype}")

ejemplo3 = np.array([1, 2, "casa"])
print(f"El ejemplo 3 es del tipo {ejemplo3.dtype}")
print(ejemplo3[0] + ejemplo3[1])

El ejemplo 1 es del tipo int64
El ejemplo 2 es del tipo float64
El ejemplo 3 es del tipo <U21
12


In [31]:
# Puedo forzar el tipo
ejemplo4 = np.array([1, 2, 3], dtype=float)
print(f"El ejemplo 4 es del tipo {ejemplo4.dtype}")

El ejemplo 4 es del tipo float64


In [32]:
# Tambien puedo convertir de tipo
ejemplo5 = ejemplo1.astype(float)
print(f"El ejemplo 1 es del tipo {ejemplo1.dtype}")
print(f"El ejemplo 5 es del tipo {ejemplo5.dtype}")

El ejemplo 1 es del tipo int64
El ejemplo 5 es del tipo float64


## Unos y ceros

NumPy tiene métodos incorporados que permiten crear arreglos de unos o ceros.

In [33]:
ceros = np.zeros(4)
print(ceros)

unos = np.ones(5)
print(unos)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [34]:
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

In [35]:
s = (3,2)
np.zeros(s, dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

## Otros metodos que permiten crear array de valores

In [36]:
rango_valores = np.arange(10)
print(rango_valores)

rango_valores = np.arange(-10, 10, 2)
print(rango_valores)

[0 1 2 3 4 5 6 7 8 9]
[-10  -8  -6  -4  -2   0   2   4   6   8]


In [37]:
rango_lineas = np.linspace(0, 10, 11)
print(rango_lineas)

rango_lineas = np.linspace(0, 5, 11)
print(rango_lineas)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [38]:
# Podemos crear matrices identidad con eye
identidad_2 = np.eye(2)
print(identidad_2)

identidad_4 = np.eye(4)
print(identidad_4)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
aleatorio = np.random.randint(0, 10, 10)
print(aleatorio)

aleatorio = np.random.rand(3, 2)
print(aleatorio)

[0 6 4 7 5 2 9 8 3 3]
[[0.50166712 0.04758563]
 [0.53290367 0.31416562]
 [0.13478005 0.85877004]]


## Axis en Numpy

En array de dos dimensiones, los axes son las direcciones a travez de las filas y columnas

In [40]:
# Veamos con np.sum() las diferencias
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)

[[1 2 3]
 [4 5 6]]


In [41]:
np.sum(matriz, axis=0)

array([5, 7, 9])

In [42]:
np.sum(matriz, axis=1)

array([ 6, 15])

In [43]:
# Sumamos todos los elementos
np.sum(matriz)

21

In [44]:
# Esto es equivalente a hacer
np.sum(np.sum(matriz, axis=1), axis=0)

21

Concatenate

In [45]:
a = np.array([[1, 1], [1, 1]])
b = np.array([[5, 5], [5, 5]])
print(a)
print(b)

[[1 1]
 [1 1]]
[[5 5]
 [5 5]]


In [46]:
# Concatenamos en direccion de las filas
np.concatenate([a,b], axis=0)

array([[1, 1],
       [1, 1],
       [5, 5],
       [5, 5]])

In [47]:
# Concatenamos en direccion de las columnas
np.concatenate([a,b], axis=1)

array([[1, 1, 5, 5],
       [1, 1, 5, 5]])

In [48]:
# Por ultimo, los array unidimensionales, tienen un solo eje
vector_1 = np.array([1,1,1])
vector_9 = np.array([9,9,9])

In [49]:
np.sum(vector_1, axis=0)

3

Si sumamos en axis=1 nos da error

In [51]:
np.sum(vector_1, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [52]:
np.concatenate([vector_1, vector_9], axis=0)

array([1, 1, 1, 9, 9, 9])

Aca tenemos una fuente de confusion ya que si fuera un array de dos dimensiones, si axis=0, se acomodaria uno abajo del otro, pero como es de una sola dimension, es en realidad uno al lado del otro. El eje en una array de una sola dimension **no** apunta hacia abajo.

Se recomienda evitar usar *axis* en array unidimensionales

Ahora si trabajamos con matrices filas, el panorama es diferente:

In [53]:
# Estos son array de dos dimensiones
arr_1 = np.array([1,1,1]).reshape([1, -1])
arr_9 = np.array([9,9,9]).reshape([1, -1])

In [54]:
np.concatenate([arr_1, arr_9], axis=0)

array([[1, 1, 1],
       [9, 9, 9]])

In [55]:
np.concatenate([arr_1, arr_9], axis=1)

array([[1, 1, 1, 9, 9, 9]])

## Reshape

Con Reshape podemos convertir array de una dimension a otra. Esta funcion es muy util

In [56]:
vector_unidimensional = np.array([0, 1, 2, 3, 4, 5])

In [58]:
# Lo transformemos en un vector columna
vector_unidimensional.reshape([-1, 1])

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [59]:
# Ahora en una matriz de 2 filas(y la cantidad de columnas necesarias)
vector_unidimensional.reshape([2, -1])

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
# O en esta otra matriz de 2 columnas(y la cantidad de filas necesarias)
vector_unidimensional.reshape([-1, 2])

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
# Probemos una de tres dimensiones
vector_unidimensional.reshape([-1, 1, 2])

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [62]:
# Tambien podemos "aplanar" matrices en un array de una dimension
a = np.array([[1, 1], [2, 2]])

print(a)

[[1 1]
 [2 2]]


In [63]:
a.reshape(-1)

array([1, 1, 2, 2])

# Operaciones

Por último, nos queda un millar de tipos de diferentes de operaciones en Numpy

In [64]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[10 11 12]
 [13 14 15]]


In [65]:
# Suma
a + b

array([[11, 13, 15],
       [17, 19, 21]])

In [66]:
# Resta
a - b

array([[-9, -9, -9],
       [-9, -9, -9]])

In [67]:
# Multiplico un array por un escalar
2*a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [68]:
# Operaciones algebraicas de matrices o vectores
a + 2*b

array([[21, 24, 27],
       [30, 33, 36]])

In [69]:
# Multiplicar elemento a elemento (esto no es una matriz, sino es el producto de dos array)
a * b

array([[10, 22, 36],
       [52, 70, 90]])

In [70]:
# Elevar al cuadrado elemento a elemento (esto no es una matriz)
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [71]:
# Dividir elemento a elemento (esto no es una matriz)
a / b

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [72]:
# Multiplicar dos matrices
a = np.array([[1,2,3],
              [4,5,6]])

c = np.array([[10,11],
              [13,14],
              [12,15]])

np.matmul(a,c)

array([[ 72,  84],
       [177, 204]])

In [73]:
np.matmul(c,a)

array([[ 54,  75,  96],
       [ 69,  96, 123],
       [ 72,  99, 126]])

In [74]:
# Transponer una matriz
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
# Recordar que para multiplicar matrices las columnas de la primera matriz
# tienen que ser igual a las filas de la segunda -> da error!
np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [76]:
np.matmul(a,b.T)

array([[ 68,  86],
       [167, 212]])

In [77]:
# Trigonometria
angles = np.array([np.pi, np.pi/2, np.pi/4, 0])
angles

array([3.14159265, 1.57079633, 0.78539816, 0.        ])

In [78]:
np.cos(angles)

array([-1.00000000e+00,  6.12323400e-17,  7.07106781e-01,  1.00000000e+00])

In [79]:
np.sin(angles)

array([1.22464680e-16, 1.00000000e+00, 7.07106781e-01, 0.00000000e+00])

In [80]:
np.tan(angles)

array([-1.22464680e-16,  1.63312394e+16,  1.00000000e+00,  0.00000000e+00])

In [81]:
cos_values = np.cos(angles)
np.arccos(cos_values)

array([3.14159265, 1.57079633, 0.78539816, 0.        ])